---
- name: Get Ceph public key
  hosts: ceph_monitor_one
  gather_facts: true
  tasks:
  - name: Setup the OSDs
    ansible.builtin.command:
          cmd: "ceph orch daemon add osd AU-SY-1-OSHV1:/dev/nvme0n1,/dev/nvme1n1"
    register: add_disk
    failed_when: add_disk != 0
    changed_when: '"Created osd(s)" in add_disk.stdout'
  - name: Waiting for 1 min to avoid a race condition
    ansible.builtin.pause:
          minutes: 1
  - name: Setup the OSDs
    ansible.builtin.command:
          cmd: "ceph orch daemon add osd AU-SY-1-OSHV2:/dev/nvme0n1,/dev/nvme1n1"
    register: add_disk
    failed_when: add_disk != 0
    changed_when: '"Created osd(s)" in add_disk.stdout'
  - name: Waiting for 1 min to avoid a race condition
    ansible.builtin.pause:
          minutes: 1
  - name: Setup the OSDs
    ansible.builtin.command:
          cmd: "ceph orch daemon add osd AU-SY-1-OSHV3:/dev/nvme0n1,/dev/nvme1n1"
    register: add_disk
    failed_when: add_disk != 0
    changed_when: '"Created osd(s)" in add_disk.stdout'
# TODO: Create Ceph FS - this also will automatically create Ceph MDS Daemons
  - name: Setup the CephFS Volume
    ansible.builtin.command:
          cmd: "ceph fs volume create ceph_data --placement=3"
    register: add_volume
    failed_when: add_volume != 0
    changed_when: '"" in add_volume.stdout'
# TODO: Add RGW
  - name: Setup the CephFS Volume
    ansible.builtin.command:
          cmd: "ceph orch apply rgw machship_rgw"
    register: add_rgw
    failed_when: add_rgw != 0
    changed_when: '"Scheduled rgw" in add_rgw.stdout'
