---
galaxy_info:
  company: Red Hat
  author: Guillaume Abrioux
  description: Handles ceph-ansible default vars for all roles
  license: Apache
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - bionic
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - system
dependencies: []
